import
  ../nimmandoc,
  hmisc/hdebug_misc,
  hmisc/other/oswrap


mcharsAlloc()
var mp = mparseAlloc(
  toCInt({mpSO, mpUTF8, mpLatiN1, mpValidate}),
  mdosOther,
  "linux".cstring
)

var file: AbsFile

if false:
  file = getAppTempFile("true") # "/usr/share/man/man1/true.1.gz"

  file.writeFile("""
.\" DO NOT MODIFY THIS FILE!  It was generated by help2man 1.47.3.
.TH TRUE "1" "March 2020" "GNU coreutils 8.32" "User Commands"
.SH NAME
true \- do nothing, successfully
.SH SYNOPSIS
.B true
[\fI\,ignored command line arguments\/\fR]
.br
.B true

\fI\,OPTION\/\fR \fI\,OPTION\/\fR

.SH DESCRIPTION
.\" Add any additional description here
.PP
Exit with a status code indicating success.
.TP
\fB\-\-help\fR
display this help and exit
.TP
\fB\-\-version\fR
output version information and exit
.PP
  """)

else:
  file = AbsFile("/usr/share/man/man1/ls.1.gz")
  # file = AbsFile("/tmp/Untitled-1.troff")



var fd = mp.mparseOpen(file.string.cstring)
mparseReadfd(mp, fd, file.string.cstring)
var meta = mparseResult(mp)
treeMan(nil, meta)

startHax()
echo treeRepr(meta.first)

let nroff = meta.first.toNRoffNode()
echo nroff.treeRepr()
