import
  ../nimmandoc,
  hmisc/hdebug_misc,
  hmisc/other/oswrap


var file: AbsFile

if false:
  file = getAppTempFile("true") # "/usr/share/man/man1/true.1.gz"

  file.writeFile("""
.\" DO NOT MODIFY THIS FILE!  It was generated by help2man 1.47.3.
.TH TRUE "1" "March 2020" "GNU coreutils 8.32" "User Commands"
.SH NAME
true \- do nothing, successfully
.SH SYNOPSIS
.B true
[\fI\,ignored command line arguments\/\fR]
.br
.B true

\fI\,OPTION\/\fR \fI\,OPTION\/\fR

.SH DESCRIPTION
.\" Add any additional description here
.PP
Exit with a status code indicating success.
.TP
\fB\-\-help\fR
display this help and exit
.TP
\fB\-\-version\fR
output version information and exit
.PP
  """)

else:
  file = findManpage("ls")
  # file = AbsFile("/usr/share/man/man1/ls.1.gz")
  # file = AbsFile("/tmp/Untitled-1.troff")

echo file

mcharsAlloc()
var mp = mparseAlloc(
  toCInt({mpSO, mpUTF8, mpLatiN1, mpValidate}),
  mdosOther,
  "linux".cstring
)


var fd = mp.mparseopen(file.string.cstring)
mparsereadfd(mp, fd, file.string.cstring)
var meta = mparseresult(mp)
# treeman(nil, meta)

starthax()
# echo treerepr(meta.first)

let nroff = meta.first.tonroffnode()
echo nroff.treeRepr()
