name: test
on: [push]
jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: alaviss/setup-nim@master
        with:
          path: '../nim'
          version: 'version-1-4'

      - name: Compile binary
        run: |
          export PATH=$HOME/.nimble/bin:$PATH
          nimble build -y -d:ssl -d:nimcore || nimble build -y -d:ssl -d:nimcore
          git clone https://github.com/nim-lang/Nim.git
          ./bin/haxdoc trail Nim/compiler/nim.nim --stdpath:Nim/lib
