name: test
on: [push]
jobs:
  compile:
    if: |
      !contains(github.event.head_commit.message, 'WIP')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: alaviss/setup-nim@master
        with:
          path: '../nim'
          version: 'version-1-4'

      - name: Run tests
        run: |
          export PATH=$HOME/.nimble/bin:$PATH
          nimble install -y
          nimble test -y -d:release
